# Generated by Django 6.0.2 on 2026-02-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bankaccount_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycashposition',
            old_name='closing_balance',
            new_name='beginning_balance',
        ),
        migrations.RenameField(
            model_name='dailycashposition',
            old_name='disbursements',
            new_name='ending_balance',
        ),
        migrations.RemoveField(
            model_name='dailycashposition',
            name='inflows',
        ),
        migrations.RemoveField(
            model_name='dailycashposition',
            name='opening_balance',
        ),
    ]
