# Generated by Django 6.0.2 on 2026-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_closing_balance_dailycashposition_beginning_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('disbursement', 'Disbursement')], max_length=20),
        ),
    ]
