# Generated by Django 6.0.2 on 2026-02-26 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('collections', 'Collections'), ('local_deposits', 'Local Deposits'), ('disbursements', 'Disbursements'), ('fund_transfers', 'Fund Transfers'), ('returned_checks', 'Returned Checks'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('interbank_transfers', 'Interbank Transfers')], max_length=50)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount')),
            ],
        ),
    ]
