# Generated by Django 6.0.2 on 2026-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashposition',
            name='collections',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashposition',
            name='disbursements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashposition',
            name='transfers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('disbursement', 'Disbursement'), ('collections', 'Collections'), ('local_deposits', 'Local Deposits'), ('fund_transfers', 'Fund Transfers'), ('returned_checks', 'Returned Checks'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('interbank_transfers', 'Interbank Transfers')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Particular',
        ),
    ]
