# Generated by Django 6.0.2 on 2026-02-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailycashposition_collections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('collections', 'Collections'), ('local_deposits', 'Local Deposits'), ('disbursement', 'Disbursement'), ('returned_checks', 'Returned Checks'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('transfer', 'Transfer'), ('fund_transfers', 'Fund Transfers'), ('interbank_transfers', 'Interbank Transfers')], max_length=50),
        ),
    ]
