# Generated by Django 6.0.2 on 2026-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashposition',
            name='returned_checks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
