# Generated by Django 6.0.2 on 2026-02-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='area',
            field=models.CharField(choices=[('main_office', 'Main Office'), ('tagoloan_parts', 'Tagoloan Parts'), ('midsayap_parts', 'Midsayap Parts'), ('valencia_parts', 'Valencia Parts')], default='main_office', max_length=50),
        ),
        migrations.AddField(
            model_name='dailycashposition',
            name='pdc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='total_pdc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('collections', 'Collections'), ('local_deposits', 'Local Deposits'), ('disbursement', 'Disbursement'), ('returned_check', 'Returned Check'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('transfer', 'Transfer'), ('fund_transfer', 'Fund Transfer'), ('interbank_transfer', 'Interbank Transfer'), ('post_dated_check', 'Post-Dated Check')], max_length=50),
        ),
    ]
