# Generated by Django 5.1.6 on 2026-03-05 03:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_created_by_transaction_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('check_no', models.CharField(blank=True, max_length=128, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('matured', 'Matured'), ('deposited', 'Deposited'), ('returned', 'Returned')], default='outstanding', max_length=32)),
                ('date_deposited', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('returned_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pdcs', to=settings.AUTH_USER_MODEL)),
                ('deposit_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdc_deposits', to='core.bankaccount')),
            ],
            options={
                'verbose_name': 'Post Dated Check',
                'verbose_name_plural': 'Post Dated Checks',
                'ordering': ['-maturity_date', '-id'],
            },
        ),
    ]
