# Generated by Django 5.1.6 on 2026-03-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_transaction_options_alter_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
