# Generated by Django 5.1.6 on 2026-03-19 00:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDailyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beginning_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('collections', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('local_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('disbursements', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('returned_checks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pdc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount')),
            ],
            options={
                'ordering': ['-date', 'bank_account__name'],
                'unique_together': {('bank_account', 'date')},
            },
        ),
    ]
