# Generated by Django 5.1.6 on 2026-03-19 00:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_bank_daily_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('office', 'Main Office'), ('quarry', 'Quarry')], default='office', max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petty Cash Fund',
                'verbose_name_plural': 'Petty Cash Funds',
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('disbursement', 'Disbursement'), ('replenishment', 'Replenishment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pcf_transactions', to=settings.AUTH_USER_MODEL)),
                ('pcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.pettycashfund')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
