# Generated by Django 5.1.6 on 2026-03-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_petty_cash_fund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pettycashfund',
            options={'ordering': ['name'], 'verbose_name': 'Petty Cash Fund', 'verbose_name_plural': 'Petty Cash Funds'},
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='location',
            field=models.CharField(choices=[('office', 'Main Office'), ('quarry', 'Quarry'), ('tagoloan', 'Tagoloan Parts'), ('midsayap', 'Midsayap Parts'), ('valencia', 'Valencia Parts'), ('other', 'Other')], default='office', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
