# Generated by Django 5.1.6 on 2026-03-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pcf_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('replenishment', 'Replenishment'), ('unreplenished', 'Unreplenished Fund')], max_length=20),
        ),
    ]
