# Generated by Django 5.1.6 on 2026-03-19 02:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pettycashtransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='min_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Alert when balance falls below this amount', max_digits=12),
        ),
    ]
