# Generated by Django 5.1.6 on 2026-03-19 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_pcf_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField()),
                ('system_balance', models.DecimalField(decimal_places=2, help_text='System balance at time of count', max_digits=12)),
                ('actual_count', models.DecimalField(decimal_places=2, help_text='Actual physical cash count', max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, help_text='Difference (actual - system)', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='core.pettycashfund')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Count',
                'verbose_name_plural': 'Cash Counts',
                'ordering': ['-count_date', '-created_at'],
            },
        ),
    ]
