# Generated by Django 6.0.3 on 2026-03-19 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_cash_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pettycashfund',
            options={'verbose_name': 'Petty Cash Fund', 'verbose_name_plural': 'Petty Cash Funds'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='location',
            field=models.CharField(choices=[('office', 'Main Office'), ('quarry', 'Quarry')], default='office', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('replenishment', 'Replenishment')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('VIEW', 'View'), ('EXPORT', 'Export')], max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BankDailyPosition',
        ),
    ]
