# Generated by Django 6.0.3 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pettycashfund_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Notes or description for this PCF'),
        ),
    ]
