# Generated by Django 5.1.6 on 2026-03-23 06:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_pcf_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('per_bank', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance per bank statement', max_digits=15)),
                ('outstanding_checks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding checks (deduct from bank)', max_digits=15)),
                ('deposit_in_transit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposits in transit (add to bank)', max_digits=15)),
                ('returned_checks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Returned checks (deduct from DCPR)', max_digits=15)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank charges not yet recorded', max_digits=15)),
                ('unbooked_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unbooked fund transfers (add to DCPR)', max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-date', '-bank_account'],
                'unique_together': {('bank_account', 'date')},
            },
        ),
    ]
