# Generated by Django 5.1.6 on 2026-03-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_bank_reconciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycashposition',
            old_name='returned_checks',
            new_name='adjustments',
        ),
        migrations.RemoveField(
            model_name='dailycashposition',
            name='transfers',
        ),
    ]
