# Generated by Django 5.1.6 on 2026-03-26 01:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_returned_checks_dailycashposition_adjustments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashposition',
            name='local_deposits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
