# Generated by Django 5.1.6 on 2026-04-20 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_transaction_from_to_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(db_index=True, default='unknown', help_text='e.g., Transaction, BankAccount, PCF, PDC', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, help_text='Username at time of action', max_length=150),
        ),
        migrations.AddField(
            model_name='collection',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='core.bankaccount'),
        ),
        migrations.AddField(
            model_name='collection',
            name='deposit_date',
            field=models.DateField(blank=True, help_text='Date when cash was deposited to bank', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('replenish', 'Replenish')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details as JSON'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('collection', 'Collection'), ('local_deposits', 'Local Deposits'), ('disbursement', 'Disbursement'), ('returned_check', 'Returned Check'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('transfer', 'Transfer'), ('fund_transfer', 'Fund Transfer'), ('fund_transfer_out', 'Fund Transfer Out'), ('fund_transfer_in', 'Fund Transfer In'), ('interbank_transfer', 'Interbank Transfer'), ('post_dated_check', 'Post-Dated Check')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'),
        ),
    ]
