# Generated by Django 5.1.6 on 2026-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_auditlog_options_remove_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='deposit_date',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this bank account starts tracking', null=True),
        ),
    ]
