# Generated by Django 5.1.6 on 2026-04-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_bank_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this PCF starts tracking', null=True),
        ),
    ]
