# Generated by Django 5.1.6 on 2026-04-27 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_pcf_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('collection', 'Collection'), ('local_deposits', 'Local Deposits'), ('disbursement', 'Disbursement'), ('returned_check', 'Returned Check'), ('bank_charges', 'Bank Charges'), ('adjustments', 'Adjustments'), ('adjustment_in', 'Adjustment (+)'), ('adjustment_out', 'Adjustment (-)'), ('transfer', 'Transfer'), ('fund_transfer', 'Fund Transfer'), ('fund_transfer_out', 'Fund Transfer Out'), ('fund_transfer_in', 'Fund Transfer In'), ('interbank_transfer', 'Interbank Transfer'), ('post_dated_check', 'Post-Dated Check')], max_length=50),
        ),
    ]
