# Generated by Django 5.1.6 on 2026-04-28 00:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_created_at_to_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance (auto-updated)', max_digits=12),
        ),
    ]
