# Generated by Django 5.1.6 on 2026-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_current_balance_to_pcf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashfund',
            name='location',
            field=models.CharField(choices=[('office', 'Main Office'), ('quarry', 'Quarry'), ('tagoloan', 'Tagoloan'), ('midsayap', 'Midsayap'), ('valencia', 'Valencia'), ('other', 'Other')], default='office', max_length=50),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='type',
            field=models.CharField(choices=[('disbursement', 'Disbursement'), ('replenishment', 'Replenishment'), ('unreplenished', 'Unreplenished')], max_length=20),
        ),
    ]
