# Generated by Django 5.1.6 on 2026-04-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_current_balance_to_pcf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycashfund',
            name='current_balance',
        ),
    ]
