# Generated by Django 5.1.6 on 2026-05-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_update_pcf_location_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdc',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
